[project]
name = "flask_app"
version = "0.1"
description = "Demo running flask with Lepton"
dependencies = ["flask"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["flask_app"]
