/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lambdalabs

import (
	"encoding/json"
)

// checks if the ListInstances200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListInstances200Response{}

// ListInstances200Response struct for ListInstances200Response
type ListInstances200Response struct {
	Data []Instance `json:"data"`
}

// NewListInstances200Response instantiates a new ListInstances200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListInstances200Response(data []Instance) *ListInstances200Response {
	this := ListInstances200Response{}
	this.Data = data
	return &this
}

// NewListInstances200ResponseWithDefaults instantiates a new ListInstances200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListInstances200ResponseWithDefaults() *ListInstances200Response {
	this := ListInstances200Response{}
	return &this
}

// GetData returns the Data field value
func (o *ListInstances200Response) GetData() []Instance {
	if o == nil {
		var ret []Instance
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListInstances200Response) GetDataOk() ([]Instance, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListInstances200Response) SetData(v []Instance) {
	o.Data = v
}

func (o ListInstances200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListInstances200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableListInstances200Response struct {
	value *ListInstances200Response
	isSet bool
}

func (v NullableListInstances200Response) Get() *ListInstances200Response {
	return v.value
}

func (v *NullableListInstances200Response) Set(val *ListInstances200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListInstances200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListInstances200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListInstances200Response(val *ListInstances200Response) *NullableListInstances200Response {
	return &NullableListInstances200Response{value: val, isSet: true}
}

func (v NullableListInstances200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListInstances200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


