/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lambdalabs

import (
	"encoding/json"
)

// checks if the ListSSHKeys200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListSSHKeys200Response{}

// ListSSHKeys200Response struct for ListSSHKeys200Response
type ListSSHKeys200Response struct {
	Data []SshKey `json:"data"`
}

// NewListSSHKeys200Response instantiates a new ListSSHKeys200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListSSHKeys200Response(data []SshKey) *ListSSHKeys200Response {
	this := ListSSHKeys200Response{}
	this.Data = data
	return &this
}

// NewListSSHKeys200ResponseWithDefaults instantiates a new ListSSHKeys200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListSSHKeys200ResponseWithDefaults() *ListSSHKeys200Response {
	this := ListSSHKeys200Response{}
	return &this
}

// GetData returns the Data field value
func (o *ListSSHKeys200Response) GetData() []SshKey {
	if o == nil {
		var ret []SshKey
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListSSHKeys200Response) GetDataOk() ([]SshKey, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListSSHKeys200Response) SetData(v []SshKey) {
	o.Data = v
}

func (o ListSSHKeys200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListSSHKeys200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableListSSHKeys200Response struct {
	value *ListSSHKeys200Response
	isSet bool
}

func (v NullableListSSHKeys200Response) Get() *ListSSHKeys200Response {
	return v.value
}

func (v *NullableListSSHKeys200Response) Set(val *ListSSHKeys200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListSSHKeys200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListSSHKeys200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListSSHKeys200Response(val *ListSSHKeys200Response) *NullableListSSHKeys200Response {
	return &NullableListSSHKeys200Response{value: val, isSet: true}
}

func (v NullableListSSHKeys200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListSSHKeys200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


