/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lambdalabs

import (
	"encoding/json"
)

// checks if the RestartInstance200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RestartInstance200Response{}

// RestartInstance200Response struct for RestartInstance200Response
type RestartInstance200Response struct {
	Data RestartInstance200ResponseData `json:"data"`
}

// NewRestartInstance200Response instantiates a new RestartInstance200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestartInstance200Response(data RestartInstance200ResponseData) *RestartInstance200Response {
	this := RestartInstance200Response{}
	this.Data = data
	return &this
}

// NewRestartInstance200ResponseWithDefaults instantiates a new RestartInstance200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestartInstance200ResponseWithDefaults() *RestartInstance200Response {
	this := RestartInstance200Response{}
	return &this
}

// GetData returns the Data field value
func (o *RestartInstance200Response) GetData() RestartInstance200ResponseData {
	if o == nil {
		var ret RestartInstance200ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *RestartInstance200Response) GetDataOk() (*RestartInstance200ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *RestartInstance200Response) SetData(v RestartInstance200ResponseData) {
	o.Data = v
}

func (o RestartInstance200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestartInstance200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableRestartInstance200Response struct {
	value *RestartInstance200Response
	isSet bool
}

func (v NullableRestartInstance200Response) Get() *RestartInstance200Response {
	return v.value
}

func (v *NullableRestartInstance200Response) Set(val *RestartInstance200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRestartInstance200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRestartInstance200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestartInstance200Response(val *RestartInstance200Response) *NullableRestartInstance200Response {
	return &NullableRestartInstance200Response{value: val, isSet: true}
}

func (v NullableRestartInstance200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestartInstance200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


