/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lambdalabs

import (
	"encoding/json"
)

// checks if the AddSSHKey200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddSSHKey200Response{}

// AddSSHKey200Response The added or generated SSH public key. If a new key pair was generated, the response body contains a `private_key` property that *must* be saved locally. Lambda Cloud does not store private keys.
type AddSSHKey200Response struct {
	Data SshKey `json:"data"`
}

// NewAddSSHKey200Response instantiates a new AddSSHKey200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddSSHKey200Response(data SshKey) *AddSSHKey200Response {
	this := AddSSHKey200Response{}
	this.Data = data
	return &this
}

// NewAddSSHKey200ResponseWithDefaults instantiates a new AddSSHKey200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddSSHKey200ResponseWithDefaults() *AddSSHKey200Response {
	this := AddSSHKey200Response{}
	return &this
}

// GetData returns the Data field value
func (o *AddSSHKey200Response) GetData() SshKey {
	if o == nil {
		var ret SshKey
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AddSSHKey200Response) GetDataOk() (*SshKey, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AddSSHKey200Response) SetData(v SshKey) {
	o.Data = v
}

func (o AddSSHKey200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddSSHKey200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableAddSSHKey200Response struct {
	value *AddSSHKey200Response
	isSet bool
}

func (v NullableAddSSHKey200Response) Get() *AddSSHKey200Response {
	return v.value
}

func (v *NullableAddSSHKey200Response) Set(val *AddSSHKey200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAddSSHKey200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAddSSHKey200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddSSHKey200Response(val *AddSSHKey200Response) *NullableAddSSHKey200Response {
	return &NullableAddSSHKey200Response{value: val, isSet: true}
}

func (v NullableAddSSHKey200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddSSHKey200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


