/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lambdalabs

import (
	"encoding/json"
)

// checks if the InstanceType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstanceType{}

// InstanceType Hardware configuration and pricing of an instance type
type InstanceType struct {
	// Name of an instance type
	Name string `json:"name"`
	// Long name of the instance type
	Description string `json:"description"`
	// Price of the instance type, in US cents per hour
	PriceCentsPerHour int32 `json:"price_cents_per_hour"`
	Specs InstanceTypeSpecs `json:"specs"`
}

// NewInstanceType instantiates a new InstanceType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceType(name string, description string, priceCentsPerHour int32, specs InstanceTypeSpecs) *InstanceType {
	this := InstanceType{}
	this.Name = name
	this.Description = description
	this.PriceCentsPerHour = priceCentsPerHour
	this.Specs = specs
	return &this
}

// NewInstanceTypeWithDefaults instantiates a new InstanceType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceTypeWithDefaults() *InstanceType {
	this := InstanceType{}
	return &this
}

// GetName returns the Name field value
func (o *InstanceType) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *InstanceType) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *InstanceType) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *InstanceType) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *InstanceType) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *InstanceType) SetDescription(v string) {
	o.Description = v
}

// GetPriceCentsPerHour returns the PriceCentsPerHour field value
func (o *InstanceType) GetPriceCentsPerHour() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PriceCentsPerHour
}

// GetPriceCentsPerHourOk returns a tuple with the PriceCentsPerHour field value
// and a boolean to check if the value has been set.
func (o *InstanceType) GetPriceCentsPerHourOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PriceCentsPerHour, true
}

// SetPriceCentsPerHour sets field value
func (o *InstanceType) SetPriceCentsPerHour(v int32) {
	o.PriceCentsPerHour = v
}

// GetSpecs returns the Specs field value
func (o *InstanceType) GetSpecs() InstanceTypeSpecs {
	if o == nil {
		var ret InstanceTypeSpecs
		return ret
	}

	return o.Specs
}

// GetSpecsOk returns a tuple with the Specs field value
// and a boolean to check if the value has been set.
func (o *InstanceType) GetSpecsOk() (*InstanceTypeSpecs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Specs, true
}

// SetSpecs sets field value
func (o *InstanceType) SetSpecs(v InstanceTypeSpecs) {
	o.Specs = v
}

func (o InstanceType) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstanceType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	toSerialize["price_cents_per_hour"] = o.PriceCentsPerHour
	toSerialize["specs"] = o.Specs
	return toSerialize, nil
}

type NullableInstanceType struct {
	value *InstanceType
	isSet bool
}

func (v NullableInstanceType) Get() *InstanceType {
	return v.value
}

func (v *NullableInstanceType) Set(val *InstanceType) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceType) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceType(val *InstanceType) *NullableInstanceType {
	return &NullableInstanceType{value: val, isSet: true}
}

func (v NullableInstanceType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


