/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lambdalabs

import (
	"encoding/json"
)

// checks if the LaunchInstance200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LaunchInstance200ResponseData{}

// LaunchInstance200ResponseData struct for LaunchInstance200ResponseData
type LaunchInstance200ResponseData struct {
	// The unique identifiers (IDs) of the launched instances. Note: if a quantity was specified, fewer than the requested quantity might have been launched.
	InstanceIds []string `json:"instance_ids"`
}

// NewLaunchInstance200ResponseData instantiates a new LaunchInstance200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLaunchInstance200ResponseData(instanceIds []string) *LaunchInstance200ResponseData {
	this := LaunchInstance200ResponseData{}
	this.InstanceIds = instanceIds
	return &this
}

// NewLaunchInstance200ResponseDataWithDefaults instantiates a new LaunchInstance200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLaunchInstance200ResponseDataWithDefaults() *LaunchInstance200ResponseData {
	this := LaunchInstance200ResponseData{}
	return &this
}

// GetInstanceIds returns the InstanceIds field value
func (o *LaunchInstance200ResponseData) GetInstanceIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.InstanceIds
}

// GetInstanceIdsOk returns a tuple with the InstanceIds field value
// and a boolean to check if the value has been set.
func (o *LaunchInstance200ResponseData) GetInstanceIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InstanceIds, true
}

// SetInstanceIds sets field value
func (o *LaunchInstance200ResponseData) SetInstanceIds(v []string) {
	o.InstanceIds = v
}

func (o LaunchInstance200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LaunchInstance200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["instance_ids"] = o.InstanceIds
	return toSerialize, nil
}

type NullableLaunchInstance200ResponseData struct {
	value *LaunchInstance200ResponseData
	isSet bool
}

func (v NullableLaunchInstance200ResponseData) Get() *LaunchInstance200ResponseData {
	return v.value
}

func (v *NullableLaunchInstance200ResponseData) Set(val *LaunchInstance200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableLaunchInstance200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableLaunchInstance200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLaunchInstance200ResponseData(val *LaunchInstance200ResponseData) *NullableLaunchInstance200ResponseData {
	return &NullableLaunchInstance200ResponseData{value: val, isSet: true}
}

func (v NullableLaunchInstance200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLaunchInstance200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


