/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lambdalabs

import (
	"encoding/json"
)

// checks if the TerminateInstance200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TerminateInstance200Response{}

// TerminateInstance200Response struct for TerminateInstance200Response
type TerminateInstance200Response struct {
	Data TerminateInstance200ResponseData `json:"data"`
}

// NewTerminateInstance200Response instantiates a new TerminateInstance200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTerminateInstance200Response(data TerminateInstance200ResponseData) *TerminateInstance200Response {
	this := TerminateInstance200Response{}
	this.Data = data
	return &this
}

// NewTerminateInstance200ResponseWithDefaults instantiates a new TerminateInstance200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTerminateInstance200ResponseWithDefaults() *TerminateInstance200Response {
	this := TerminateInstance200Response{}
	return &this
}

// GetData returns the Data field value
func (o *TerminateInstance200Response) GetData() TerminateInstance200ResponseData {
	if o == nil {
		var ret TerminateInstance200ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *TerminateInstance200Response) GetDataOk() (*TerminateInstance200ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *TerminateInstance200Response) SetData(v TerminateInstance200ResponseData) {
	o.Data = v
}

func (o TerminateInstance200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TerminateInstance200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableTerminateInstance200Response struct {
	value *TerminateInstance200Response
	isSet bool
}

func (v NullableTerminateInstance200Response) Get() *TerminateInstance200Response {
	return v.value
}

func (v *NullableTerminateInstance200Response) Set(val *TerminateInstance200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableTerminateInstance200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableTerminateInstance200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTerminateInstance200Response(val *TerminateInstance200Response) *NullableTerminateInstance200Response {
	return &NullableTerminateInstance200Response{value: val, isSet: true}
}

func (v NullableTerminateInstance200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTerminateInstance200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


