/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lambdalabs

import (
	"encoding/json"
)

// checks if the GetInstance200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetInstance200Response{}

// GetInstance200Response struct for GetInstance200Response
type GetInstance200Response struct {
	Data Instance `json:"data"`
}

// NewGetInstance200Response instantiates a new GetInstance200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetInstance200Response(data Instance) *GetInstance200Response {
	this := GetInstance200Response{}
	this.Data = data
	return &this
}

// NewGetInstance200ResponseWithDefaults instantiates a new GetInstance200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetInstance200ResponseWithDefaults() *GetInstance200Response {
	this := GetInstance200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetInstance200Response) GetData() Instance {
	if o == nil {
		var ret Instance
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetInstance200Response) GetDataOk() (*Instance, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetInstance200Response) SetData(v Instance) {
	o.Data = v
}

func (o GetInstance200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetInstance200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableGetInstance200Response struct {
	value *GetInstance200Response
	isSet bool
}

func (v NullableGetInstance200Response) Get() *GetInstance200Response {
	return v.value
}

func (v *NullableGetInstance200Response) Set(val *GetInstance200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetInstance200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetInstance200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetInstance200Response(val *GetInstance200Response) *NullableGetInstance200Response {
	return &NullableGetInstance200Response{value: val, isSet: true}
}

func (v NullableGetInstance200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetInstance200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


