# https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/
# https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/
# https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration

kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1

address: 10.0.68.34
port: 10250

authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 2m0s
    enabled: true
  x509:
    clientCAFile: "/etc/kubernetes/pki/ca.crt"
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 5m0s
    cacheUnauthorizedTTL: 30s
clusterDomain: cluster.local
hairpinMode: hairpin-veth
readOnlyPort: 0
cgroupDriver: cgroupfs
cgroupRoot: "/"
featureGates:
  RotateKubeletServerCertificate: true

protectKernelDefaults: true
serializeImagePulls: false

serverTLSBootstrap: true
tlsCipherSuites:
  - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
  - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
  - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
  - TLS_RSA_WITH_AES_256_GCM_SHA384
  - TLS_RSA_WITH_AES_128_GCM_SHA256

containerRuntimeEndpoint: unix:///run/containerd/containerd.sock

# running with swap on is not supported, please disable swap! or set --fail-swap-on
failSwapOn: false

# registerWithTaints
registerNode: true

registerWithTaints:
  - key: lepton.io/provider
    value: lambda
    effect: NoSchedule
  - key: nvidia.com/gpu
    value: ""
    effect: NoSchedule
