apiVersion: v1
kind: Pod
metadata:
  name: nginx

spec:
  hostNetwork: true

  tolerations:
    - key: lepton.io/provider
      value: lambda
      operator: Equal
      effect: NoSchedule
    - key: nvidia.com/gpu
      value: ""
      operator: Exists
      effect: NoSchedule

  containers:
    - name: nginx
      image: nginx:latest
