---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  selector:
    matchLabels:
      run: my-app
  replicas: 1
  template:
    metadata:
      labels:
        run: my-app
    spec:
      hostNetwork: true

      tolerations:
        - key: lepton.io/provider
          value: lambda
          operator: Equal
          effect: NoSchedule
        - key: nvidia.com/gpu
          value: ""
          operator: Exists
          effect: NoSchedule

      containers:
        - name: my-app
          image: lvthillo/python-flask-docker
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    run: my-app
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: my-app
