{{ if .Values.apiServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apiServer.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.apiServer.name }}
spec:
  replicas: {{ .Values.apiServer.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.apiServer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.apiServer.name }}
    spec:
      serviceAccountName: {{ .Values.apiServer.name }}
      containers:
        - name: {{ .Values.apiServer.name }}
          image: {{ .Values.apiServer.image.repository }}:{{ .Values.apiServer.image.tag }}
          imagePullPolicy: {{ .Values.apiServer.image.pullPolicy }}
          resources:
            requests:
              memory: {{ .Values.apiServer.service.resources.requests.memory }}
              cpu: {{ .Values.apiServer.service.resources.requests.cpu }}
            limits:
              memory: {{ .Values.apiServer.service.resources.limits.memory }}
              cpu: {{ .Values.apiServer.service.resources.limits.cpu }}
          command: [ "/app/{{ .Values.apiServer.name }}" ]
          args:
            - "--cluster-name"
            - "{{ .Values.clusterName }}"
            - "--namespace"
            - {{ .Release.Namespace | quote }}
            - "--service-account-name"
            - "{{ .Values.apiServer.name }}"
            - "--bucket-name"
            - "{{ .Values.apiServer.bucketName }}"
            - "--certificate-arn"
            - "{{ .Values.apiServer.certificateArn }}"
            - "--root-domain"
            - "{{ .Values.apiServer.rootDomain }}"
            - "--api-token"
            - "{{ .Values.apiServer.apiToken }}"
            - "--photon-prefix"
            - "{{ .Values.apiServer.photonPrefix }}"
            - "--cell-name"
            - "{{ .Values.apiServer.cellName }}"
            - "--dynamodb-name"
            - "{{ .Values.apiServer.dynamodbName }}"
            - "--enable-tuna={{ .Values.apiServer.enableTuna }}"
          ports:
            - containerPort: {{ .Values.apiServer.service.port }}
{{ end }}
