apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiServer.name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.apiServer.name }}
  ports:
    - name: http
      port: {{ .Values.apiServer.service.port }}
      targetPort: {{ .Values.apiServer.service.port }}
