{{ if .Values.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.web.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.web.name }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.web.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.web.name }}
    spec:
      securityContext:
        # nginx's user id is 101
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
      containers:
        - name: {{ .Values.web.name }}
          image: {{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              memory: {{ .Values.web.service.resources.requests.memory }}
              cpu: {{ .Values.web.service.resources.requests.cpu }}
            limits:
              memory: {{ .Values.web.service.resources.limits.memory }}
              cpu: {{ .Values.web.service.resources.limits.cpu }}
          ports:
            - containerPort: {{ .Values.web.service.port }}
{{ end }}
