{{ if .Values.metering.syncEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metering.name }}-{{ .Values.metering.syncName }}-deployment
  namespace: metering
  labels:
    app: {{ .Values.metering.name }}
spec:
  replicas: {{ .Values.metering.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.metering.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.metering.name }}
    spec:
      serviceAccountName: {{ .Values.metering.serviceAccountName }}
      containers:
      - name: {{ .Values.metering.name }}-{{ .Values.metering.syncName }}-container
        env:
        - name: AURORA_USERNAME
          valueFrom:
            secretKeyRef:
              name: mothership-rds-aurora-secret
              key: username
        - name: AURORA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mothership-rds-aurora-secret
              key: password
        args:
        - "metering"
        - "sync"
        - "--db-driver-name={{ .Values.metering.auroraDbDriver }}"
        - "--db-host={{ .Values.metering.auroraDbHost }}"
        - "--db-region={{ .Values.metering.region }}"
        - "--db-port={{ .Values.metering.auroraDbPort }}"
        - "--db-name={{ .Values.metering.auroraDbName }}"
        - "--db-user=$(AURORA_USERNAME)"
        - "--db-password=$(AURORA_PASSWORD)"
        - "--opencost-namespace={{ .Values.metering.kubecostNamespace }}"
        - "--opencost-service-name={{ .Values.metering.kubecostServiceName }}"
        - "--opencost-service-port={{ .Values.metering.kubecostPort}}"
        - "--mothership-region={{ .Values.metering.region }}"
        - "--enable-compute"
        - "--enable-storage"
        - "--in-cluster"
        - "--cluster-name={{ .Values.metering.clusterName }}"
        image: {{ .Values.metering.image.repository }}:{{ .Values.metering.image.tag }}
        imagePullPolicy: {{ .Values.metering.image.pullPolicy }}
        resources:
          requests:
            cpu: {{ .Values.metering.service.resources.requests.cpu }}
            memory: {{ .Values.metering.service.resources.requests.memory }}
        ports:
        - name: metrics
          containerPort: {{ .Values.metering.metricsPort }}
          protocol: TCP
{{ end }}
