# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
kubelet:
  enabled: true

  # use the same default value as the helm chart
  namespace: kube-system

  serviceMonitor:
    # scraping /metrics/cadvisor from kubelet's service
    cAdvisor: true

    # upstream kube-prometheus-stack chart by default
    # drops some metrics they think not useful
    # add the useful ones back
    # ref. https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L1166-L1218
    cAdvisorMetricRelabelings:

      # drop less useful container CPU metrics
      - sourceLabels:
        - __name__
        action: drop
        regex: container_cpu_(cfs_throttled_seconds_total|load_average_10s|system_seconds_total|user_seconds_total)

      # drop less useful, always zero container file system metrics
      - sourceLabels:
        - __name__
        action: drop
        regex: container_fs_(io_current|io_time_seconds_total|io_time_weighted_seconds_total|reads_merged_total|sector_reads_total|sector_writes_total|writes_merged_total)

      # drop less useful, always zero container memory metrics
      - sourceLabels:
        - __name__
        action: drop
        regex: container_memory_(mapped_file|swap)

      # less useful container process metrics
      # but do not drop "container_spec.*"
      # TODO: drop this when we find the equivalent in kube-state-metrics

      # cgroup metrics with no pod
      - sourceLabels:
        - id
        - pod
        action: drop
        regex: .+;
