apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mothership-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - backend:
          service:
            name: mothership-service
            port:
              number: 80
        path: /
        pathType: Prefix
