apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mothership.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.mothership.name }}
spec:
  replicas: {{ .Values.mothership.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mothership.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mothership.name }}
    spec:
      containers:
        - name: {{ .Values.mothership.name }}
          image: {{ .Values.mothership.image.repository }}:{{ .Values.mothership.image.tag }}
          imagePullPolicy: {{ .Values.mothership.image.pullPolicy }}
          resources:
            requests:
              memory: {{ .Values.mothership.service.resources.requests.memory }}
              cpu: {{ .Values.mothership.service.resources.requests.cpu }}
          command: [ "/mothership" ]
          ports:
            - containerPort: {{ .Values.mothership.service.port }}
