apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/part-of: kube-prometheus-stack
    release: kube-prometheus-stack
  name: kube-prometheus-stack-lepton-deployment.rules
  namespace: kube-prometheus-stack
spec:
  groups:
    - name: lepton-deployment.rules
      rules:
        - alert: UserPodNotReady
          annotations:
            description: User pods are not ready for 20 mins
            summary: User pods are not ready for 20 mins
          expr: |-
            kube_pod_status_phase{namespace=~"ws-.+", phase=~"Pending|Unknown"} > 0
          for: 20m
          labels:
            severity: critical
        - alert: UserDeploymentNotReady
          annotations:
            description: User deployments are not ready for 20 mins
            summary: User deployments are not ready for 20 mins
          expr: |-
            kube_deployment_status_condition{namespace=~"ws-.+", status=~"false|unknown"} > 0
          for: 20m
          labels:
            severity: critical
