apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/part-of: kube-prometheus-stack
    release: kube-prometheus-stack
  name: kube-prometheus-stack-lepton-system-components.rules
  namespace: kube-prometheus-stack
spec:
  groups:
    - name: lepton-system-components.rules
      rules:
        - alert: APIServerNotReady
          annotations:
            description: API Server is not ready for 5 mins
            runbook_url: https://todo.com
            summary: API Server is not ready for 5 mins
          expr: |-
            kube_deployment_status_condition{deployment="lepton-api-server", status=~"false|unknown"} > 0
          for: 5m
          labels:
            severity: critical
        - alert: DeploymentOperatorNotReady
          annotations:
            description: Deployment operator is not ready for 5 mins
            runbook_url: https://todo.com
            summary: Deployment operator is not ready for 5 mins
          expr: |-
            kube_deployment_status_condition{deployment="deployment-operator", status=~"false|unknown"} > 0
          for: 5m
          labels:
            severity: critical
