apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/part-of: kube-prometheus-stack
    release: kube-prometheus-stack
  name: kube-prometheus-stack-metering.rules
  namespace: kube-prometheus-stack
spec:
  groups:
    - name: metering.rules
      rules:
        - alert: NoHourlyMeteringUpdate
          annotations:
            description: No hourly metering data updates for the past 2 hours
            summary: No hourly metering data updates
          expr: |-
            increase(lepton_metering_update_operations_total{table_name=~".+_hourly"}[2h]) < 1
          for: 1m
          labels:
            severity: critical
        - alert: NoFineGrainMeteringUpdate
          annotations:
            description: No fine-grain metering data updates for the past 20 mins
            summary: No fine-grain metering data updates
          expr: |-
            increase(lepton_metering_update_operations_total{table_name=~".+_fine_grain"}[20m]) < 1
          for: 1m
          labels:
            severity: critical
        - alert: NoMeteringSync
          annotations:
            description: Metering last sync updated < 1 row for the past 2 hours
            summary: No metering data updates
          expr: |-
            absent_over_time(lepton_metering_last_sync_updated_rows[2h])
          for: 1m
          labels:
            severity: critical
        - alert: MeteringRequestFailureRate
          annotations:
            description: Metering request failure rate at {{ $value }}/per hour, (> 10)
            summary: Metering request failure rate high
          expr: |-
            increase(promhttp_metric_handler_requests_total{job="metering-metrics", code!="200"}[1h]) > 10
          for: 1m
          labels:
            severity: critical
