apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/part-of: kube-prometheus-stack
    release: kube-prometheus-stack
  name: kube-prometheus-stack-system-components.rules
  namespace: kube-prometheus-stack
spec:
  groups:
    - name: system-components.rules
      rules:
        - alert: SystemDeploymentNotReady
          annotations:
            description: System deployments (not in the ws-* namespace) is not ready for 5 mins
            runbook_url: https://todo.com
            summary: System deployments (not in the ws-* namespace) is not ready for 5 mins
          expr: |-
            kube_deployment_status_condition{namespace!~"ws-.+", status=~"false|unknown"} > 0
          for: 10m
          labels:
            severity: critical
        - alert: SystemPodsNotReady
          annotations:
            description: System pods (not in the ws-* namespace) not running for 5 min
            runbook_url: https://todo.com
            summary: System pods (not in the ws-* namespace) not running for 5 min
          expr: |-
            kube_pod_status_phase{namespace!~"ws-.+", phase=~"Pending|Unknown"} > 0
          for: 5m
          labels:
            severity: critical
        - alert: SystemPodFailed
          annotations:
            description: System pods (pods not in the ws-* namespace) failed
            runbook_url: https://todo.com
            summary: System pods (pods not in the ws-* namespace) failed
          expr: |-
            kube_pod_status_phase{namespace!~"ws-.+", phase="Failed"} > 0
          for: 1m
          labels:
            severity: critical
        - alert: PVReleased
          annotations:
            description: PV is released/unbound for more than 5 min
            runbook_url: https://todo.com
            summary: Number of released/unbound PV is elevated
          expr: |-
            kube_persistentvolume_status_phase{phase=~"Released|Available|Failed"} > 0
          for: 5m
          labels:
            severity: critical
        - alert: PVPending
          annotations:
            description: PV is pending for more than 5 min
            runbook_url: https://todo.com
            summary: PV is pending for more than 5 min
          expr: |-
            kube_persistentvolume_status_phase{phase=~"Pending"} > 0
          for: 5m
          labels:
            severity: critical
        - alert: NodeFilesystemAlmostFull
          annotations:
            description: Node filesystem is almost full
            runbook_url: https://todo.com
            summary: Node filesystem is almost full
          expr: |-
            node_filesystem_avail_bytes / node_filesystem_size_bytes < 0.2
          for: 1m
          labels:
            severity: critical
