{
 "title": "Lepton Cluster",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Top Line Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Workspaces",
   "type": "stat",
   "description": "Number of active workspaces",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_status_phase{phase=\"Active\", namespace=~\"ws-.*\"})"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "count(kube_deployment_status_replicas {namespace=~\"ws-.*\"} == kube_deployment_status_replicas_ready {namespace=~\"ws-.*\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "count(kube_deployment_status_replicas {namespace=~\"ws-.*\"} != kube_deployment_status_replicas_ready {namespace=~\"ws-.*\"})",
     "legendFormat": "Not ready"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{namespace=~\"ws-.*\", condition=\"true\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_status_ready{namespace=~\"ws-.*\", condition=\"false\"})",
     "legendFormat": "Not Ready"
    }
   ]
  },
  {
   "title": "Control Plane Success RPS ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(lepton_http_requests_total{status_code=~\"2.+\"}[1m]))"
    },
    {
     "expr": "sum(rate(lepton_http_requests_total{status_code=~\"4.+\"}[1m]))"
    }
   ]
  },
  {
   "title": "Control Plane Error RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(lepton_http_requests_total{status_code=~\"5.+\"}[1m]))"
    }
   ]
  },
  {
   "title": "Control Plane Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, method, api) (rate(lepton_http_requests_latency_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Number of Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(label_beta_kubernetes_io_instance_type) (kube_node_labels{label_beta_kubernetes_io_instance_type=~\".+\", job=\"kube-state-metrics\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Number of Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(phase) (kube_pod_status_phase{job=\"kube-state-metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Allocation & Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"})"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\", node=~\".+\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "CPU Allocation & Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\", job=\"kube-state-metrics\"})"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", node=~\".+\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  { "title": "Kube Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "API Server Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(increase(apiserver_request_duration_seconds_bucket{job=\"apiserver\",subresource=\"\",verb!=\"WATCH\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "etcd Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum by (le)(increase(etcd_request_duration_seconds_bucket{job=\"apiserver\"}[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}