version: "3.8"

services:
    controller:
        image: 605454121064.dkr.ecr.us-east-1.amazonaws.com/lepton:tuna-runner-0.1.8
        command: lep ph run -n controller -m controller.py -p 21001
        shm_size: 1gb
        volumes:
            - .:/workspace
        working_dir: /workspace
        network_mode: "host"
        ports:
            - "21001:21001"
    worker:
        image: 605454121064.dkr.ecr.us-east-1.amazonaws.com/lepton:tuna-runner-0.1.8
        command: lep ph run -n ft-worker -m ft_worker.py -p 21002
        shm_size: 1gb
        volumes:
            - .:/workspace
        working_dir: /workspace
        environment:
            - USE_INT=1
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [gpu]
        network_mode: "host"
        ports:
            - "21002:21002"
        depends_on:
            - controller
    frontend:
        image: 605454121064.dkr.ecr.us-east-1.amazonaws.com/lepton:tuna-runner-0.1.8
        command: lep ph run -n frontend -m frontend.py -p 8080
        shm_size: 1gb
        volumes:
            - .:/workspace
        working_dir: /workspace
        network_mode: "host"
        ports:
            - "8080:8080"
        depends_on:
            - controller
            - worker
