version: "3.8"

services:
    tuna:
        image: 605454121064.dkr.ecr.us-east-1.amazonaws.com/lepton:tuna-23.02
        command: lep ph run -n tuna -m tuna-inference.py
        shm_size: 1gb
        volumes:
            - .:/workspace
        working_dir: /workspace
        network_mode: "host"
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [gpu]
