mothership:
  name: mothership
  replicaCount: 1
  image:
    repository: 605454121064.dkr.ecr.us-east-1.amazonaws.com/lepton-mothership
    tag: "latest"
    pullPolicy: Always
  service:
    port: 15213
    resources:
      requests:
        memory: "4096Mi"
        cpu: "2"
  serviceAccountRoleArn: "arn:aws:iam::605454121064:role/mothership-role"
  certificateArn: "arn:aws:acm:us-east-1:605454121064:certificate/d8d5e0e1-ecc5-4716-aa79-01625e60704d"
  apiToken: "cd17aef833bb660da98e7235b57ffe8d"
  rootDomain: "cloud.lepton.ai"
  sharedAlbRootDomain: "dev.lepton.ai"
  sharedALBRoute53ZoneID: "Z07918881RBIVGJY04WCJ"
  deploymentEnvironment: "DEV"
