# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
defaultRules:

  create: true

  rules:
    alertmanager: true
    etcd: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false

  appNamespacesTarget: ${alertmanager_target_namespaces}

  # disabled PrometheusRule alerts
  disabled: {}
