# https://github.com/NVIDIA/gpu-operator/blob/master/deployments/gpu-operator/Chart.yaml
# https://github.com/NVIDIA/gpu-operator/blob/master/deployments/gpu-operator/values.yaml
toolkit:
  enabled: true
  repository: nvcr.io/nvidia/k8s
  image: container-toolkit
  version: ${toolkit_version}

dcgmExporter:
  enabled: true

  # repository: nvcr.io/nvidia/k8s
  repository: ${dcgm_exporter_container_repo}

  image: dcgm-exporter
  version: 3.1.8-3.1.5-ubuntu20.04

  imagePullPolicy: IfNotPresent

daemonsets:
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule

    # TODO: add this taint to all GPU nodes to disable calico?
    # TODO: tolerate this to run GPU operator components on satellite nodes
    # - key: lepton.io/provider
    #   operator: Exists
    #   effect: NoSchedule

operator:
  # https://catalog.ngc.nvidia.com/orgs/nvidia/containers/gpu-operator/tags
  repository: nvcr.io/nvidia
  image: gpu-operator

  # default to chart value
  # version: ""

  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Equal
      value: ""
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      operator: Equal
      value: ""
      effect: NoSchedule

    # TODO: add this taint to all GPU nodes to disable calico?
    # TODO: tolerate this to run GPU operator components on satellite nodes
    # - key: lepton.io/provider
    #   operator: Exists
    #   effect: NoSchedule

node-feature-discovery:
  enableNodeFeatureApi: true
  worker:
    tolerations:
      - key: node-role.kubernetes.io/master
        operator: Equal
        value: ""
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Equal
        value: ""
        effect: NoSchedule
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule

    # TODO: add this taint to all GPU nodes to disable calico?
    # TODO: tolerate this to run GPU operator components on satellite nodes
    # - key: lepton.io/provider
    #   operator: Exists
    #   effect: NoSchedule

validator:
  # https://catalog.ngc.nvidia.com/orgs/nvidia/teams/cloud-native/containers/gpu-operator-validator/tags
  repository: nvcr.io/nvidia/cloud-native
  image: gpu-operator-validator

  # default to chart value
  # version: ""

  plugin:
    env:
      # disable plugin workload validation by default to avoid UnexpectedAdmissionError
      # ref. https://github.com/NVIDIA/gpu-operator/commit/d8944e115b8bc1cd6f74ae39ad8a8080336ed9e3
      # ref. https://github.com/NVIDIA/gpu-operator/commit/b2e51a407b74c285ee557812dfdc375250649d6c
      - name: WITH_WORKLOAD
        value: "false"
