#!/usr/bin/env python
"""Generate the Python SDK reference pages (fumadocs MDX) for the docs site.

The script introspects the installed ``leptonai`` package and writes:

- one page for ``leptonai.api.v2.APIClient`` (constructor, properties, errors),
- one page per resource group reachable from the client (``client.job`` ...),
- one page for the endpoint-calling ``leptonai.client.Client``,
- one page per module under ``leptonai.api.v2.types`` with a field table per
  pydantic model and a member table per enum,
- ``meta.json`` files so the pages show up in the sidebar.

Usage::

    python scripts/gen_sdk_reference.py --out <docs>/src/content/docs/reference/api

Existing ``index.mdx`` at the output root (the hand-written tutorial) is kept.
Pages previously produced by this script are replaced.
"""

from __future__ import annotations

import argparse
import enum
import importlib
import inspect
import json
import pkgutil
import re
import textwrap
import types as pytypes
import typing
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Set, Tuple

from pydantic import BaseModel
from pydantic_core import PydanticUndefined

import leptonai
import leptonai.api.v2 as api_v2
import leptonai.api.v2.client as client_module
from leptonai.api.v2 import types as sdk_types
from leptonai.api.v2.api_resource import APIResourse
from leptonai.api.v2.client import APIClient
from leptonai.api.v2.workspace_record import WorkspaceRecord

MARKER = "Generated by scripts/gen_sdk_reference.py"
NoneType = type(None)

# ``client.deployment`` / ``client.pod`` are properties that dispatch between the
# new endpoint/devpod API and the legacy deployment API. The page documents the
# new class and lists legacy-only methods separately.
DISPATCHED = {
    "deployment": ("_endpoint_api", "_deployment_legacy"),
    "pod": ("_devpod_api", "_pod_legacy"),
}

PREFERRED_ORDER = [
    "deployment",
    "pod",
    "job",
    "nodegroup",
    "shapes",
    "secret",
    "ingress",
    "log",
    "template",
    "finetune",
    "raycluster",
    "slurm",
]

# Fallback one-liners when the resource class has no docstring.
RESOURCE_BLURBS = {
    "deployment": (
        "Endpoints (deployments): create, update, restart and inspect inference"
        " endpoints."
    ),
    "pod": "Dev pods: create, start, stop and inspect interactive development pods.",
    "job": "Batch jobs: create, list, stop, clone and inspect jobs.",
    "nodegroup": "Dedicated node groups and the nodes in them.",
    "shapes": "Resource shapes available to the workspace.",
    "secret": "Workspace secrets.",
    "ingress": "Custom-domain ingress and traffic weights across endpoints.",
    "log": "Log retrieval for endpoints, pods and jobs.",
    "template": "Workload templates.",
    "finetune": "Fine-tuning jobs.",
    "raycluster": "Ray clusters.",
    "slurm": "Managed Slurm clusters, jobs and dev pods.",
}


# --------------------------------------------------------------------------- #
# Markdown / MDX helpers
# --------------------------------------------------------------------------- #

ROLE_RE = re.compile(
    r":(?:class|attr|mod|func|meth|obj|data|exc|ref|const|term):`~?([^`]+)`"
)
CODE_SPAN_RE = re.compile(r"(`[^`]*`)")
SECTION_RE = re.compile(
    r"^(Args|Arguments|Parameters|Returns|Return|Raises|Yields|Attributes|"
    r"Note|Notes|Usage|Example|Examples|Warning|Warnings|See Also):\s*$"
)
CODE_SECTIONS = {"Usage", "Example", "Examples"}


def escape_text(text: str) -> str:
    """Escape characters MDX would parse as JSX or expressions, outside code spans."""
    parts = CODE_SPAN_RE.split(text)
    for i in range(0, len(parts), 2):
        seg = parts[i]
        seg = seg.replace("{", "\\{").replace("}", "\\}").replace("<", "\\<")
        parts[i] = seg
    out = "".join(parts)
    if out.startswith("#"):
        out = "\\" + out
    return out


def inline_md(text: str) -> str:
    text = ROLE_RE.sub(lambda m: f"`{m.group(1)}`", text)
    text = text.replace("``", "`")
    return escape_text(text)


def cell(text: str) -> str:
    """Make text safe for a GFM table cell."""
    return inline_md(" ".join(text.split())).replace("|", "\\|")


def code(text: str) -> str:
    return "`" + text.replace("`", "'") + "`"


def own_doc(obj: Any) -> Optional[str]:
    """Docstring defined on the object itself, ignoring inherited ones."""
    if inspect.isclass(obj):
        doc = obj.__dict__.get("__doc__")
    else:
        doc = getattr(obj, "__doc__", None)
    if not doc or not doc.strip():
        return None
    return inspect.cleandoc(doc)


def first_line(doc: Optional[str]) -> str:
    if not doc:
        return ""
    para = doc.strip().split("\n\n", 1)[0]
    return " ".join(para.split())


def docstring_to_md(doc: Optional[str]) -> str:
    """Render a Google/RST-flavoured docstring as MDX-safe markdown."""
    if not doc:
        return ""
    lines = inspect.cleandoc(doc).splitlines()
    out: List[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        m = SECTION_RE.match(line.strip())
        if m and not line.startswith((" ", "\t")):
            name = m.group(1)
            block: List[str] = []
            i += 1
            while i < len(lines) and (
                lines[i].strip() == "" or lines[i].startswith((" ", "\t"))
            ):
                block.append(lines[i])
                i += 1
            while block and block[-1].strip() == "":
                block.pop()
            body = textwrap.dedent("\n".join(block))
            out.append("")
            out.append(f"**{name}:**")
            out.append("")
            if name in CODE_SECTIONS:
                out.extend(["```python", body, "```"])
            else:
                items: List[str] = []
                for bl in body.splitlines():
                    if not bl.strip():
                        continue
                    if bl.startswith((" ", "\t")) and items:
                        items[-1] += " " + bl.strip()
                    else:
                        items.append(bl.strip())
                out.extend("- " + inline_md(it) for it in items)
            out.append("")
            continue
        if line.startswith("    ") and line.strip():
            # RST-style literal block: indented lines outside a named section.
            block: List[str] = []
            while i < len(lines) and (
                lines[i].startswith("    ")
                or (
                    lines[i].strip() == ""
                    and i + 1 < len(lines)
                    and lines[i + 1].startswith("    ")
                )
            ):
                block.append(lines[i])
                i += 1
            code_text = textwrap.dedent("\n".join(block)).rstrip()
            out += ["", "```python", code_text, "```", ""]
            continue
        out.append(inline_md(line))
        i += 1
    text = "\n".join(out)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def slug(name: str) -> str:
    return re.sub(r"[^a-z0-9_\- ]", "", name.lower()).replace(" ", "-")


def frontmatter(title: str, description: str) -> str:
    return (
        f"---\ntitle: {json.dumps(title)}\ndescription:"
        f" {json.dumps(' '.join(description.split()))}\n---\n\n{{/* {MARKER} from"
        f" leptonai {leptonai.__version__}. Do not edit by hand. */}}\n"
    )


# --------------------------------------------------------------------------- #
# Type formatting
# --------------------------------------------------------------------------- #


def is_sdk_type(obj: Any) -> bool:
    return (
        inspect.isclass(obj)
        and obj.__module__.startswith("leptonai.api.v2.types")
        and (issubclass(obj, BaseModel) or issubclass(obj, enum.Enum))
    )


def type_link(cls: type, route: str) -> str:
    module = cls.__module__.rsplit(".", 1)[-1]
    return f"{route}/types/{module}#{slug(cls.__name__)}"


def fmt_type(tp: Any, refs: Optional[Set[type]] = None) -> str:
    if refs is None:
        refs = set()
    if tp is inspect.Parameter.empty or tp is inspect.Signature.empty:
        return ""
    if tp is None or tp is NoneType:
        return "None"
    if tp is Ellipsis:
        return "..."
    if isinstance(tp, str):
        return tp
    if isinstance(tp, list):
        return "[" + ", ".join(fmt_type(a, refs) for a in tp) + "]"
    if isinstance(tp, typing.ForwardRef):
        return tp.__forward_arg__
    if isinstance(tp, typing.TypeVar):
        return tp.__name__
    if tp is typing.Any:
        return "Any"
    origin = typing.get_origin(tp)
    args = typing.get_args(tp)
    if origin is typing.Union or origin is getattr(pytypes, "UnionType", None):
        non_none = [a for a in args if a is not NoneType]
        if len(args) == 2 and len(non_none) == 1:
            return f"Optional[{fmt_type(non_none[0], refs)}]"
        return "Union[" + ", ".join(fmt_type(a, refs) for a in args) + "]"
    if origin is typing.Literal:
        return "Literal[" + ", ".join(repr(a) for a in args) + "]"
    if origin is not None:
        name = getattr(origin, "__name__", None) or str(origin)
        name = {
            "list": "List",
            "dict": "Dict",
            "set": "Set",
            "frozenset": "FrozenSet",
            "tuple": "Tuple",
            "type": "Type",
        }.get(name, name)
        if not args:
            return name
        return f"{name}[" + ", ".join(fmt_type(a, refs) for a in args) + "]"
    if inspect.isclass(tp):
        if is_sdk_type(tp):
            refs.add(tp)
        return tp.__name__
    return repr(tp).replace("typing.", "")


def fmt_default(value: Any) -> str:
    if isinstance(value, enum.Enum):
        return f"{type(value).__name__}.{value.name}"
    if isinstance(value, BaseModel):
        return f"{type(value).__name__}(...)"
    if inspect.isclass(value) or inspect.isfunction(value):
        return value.__name__
    text = repr(value)
    if len(text) > 48:
        text = text[:45] + "..."
    return text


def typed(tp: Any, route: str) -> str:
    """Inline-code type plus links to SDK types it references."""
    refs: Set[type] = set()
    text = fmt_type(tp, refs)
    if not text:
        return ""
    if len(refs) == 1:
        cls = next(iter(refs))
        return f"[{code(text)}]({type_link(cls, route)})"
    out = code(text)
    if refs:
        links = ", ".join(
            f"[{c.__name__}]({type_link(c, route)})"
            for c in sorted(refs, key=lambda c: c.__name__)
        )
        out += f" (see {links})"
    return out


# --------------------------------------------------------------------------- #
# Callable rendering
# --------------------------------------------------------------------------- #


def resolve_hints(fn: Any) -> Dict[str, Any]:
    try:
        return typing.get_type_hints(fn)
    except Exception:
        return dict(getattr(fn, "__annotations__", {}) or {})


def build_signature(
    prefix: str, fn: Any, skip_first: bool
) -> Tuple[str, List[Tuple[str, Any, Any]], Any]:
    """Return (signature text, [(name, annotation, default)], return annotation)."""
    sig = inspect.signature(fn)
    hints = resolve_hints(fn)
    params: List[str] = []
    details: List[Tuple[str, Any, Any]] = []
    items = list(sig.parameters.items())
    if skip_first and items and items[0][0] in ("self", "cls"):
        items = items[1:]
    seen_star = False
    for name, p in items:
        if p.kind == p.KEYWORD_ONLY and not seen_star:
            params.append("*")
            seen_star = True
        ann = hints.get(name, p.annotation)
        text = name
        if p.kind == p.VAR_POSITIONAL:
            text = "*" + name
            seen_star = True
        elif p.kind == p.VAR_KEYWORD:
            text = "**" + name
        if ann is not inspect.Parameter.empty:
            text += f": {fmt_type(ann)}"
        if p.default is not inspect.Parameter.empty:
            sep = " = " if ann is not inspect.Parameter.empty else "="
            text += sep + fmt_default(p.default)
        params.append(text)
        details.append((name, ann, p.default))
    ret = hints.get("return", sig.return_annotation)
    ret_text = f" -> {fmt_type(ret)}" if ret is not inspect.Signature.empty else ""
    one_line = f"{prefix}({', '.join(params)}){ret_text}"
    if len(one_line) <= 88:
        return one_line, details, ret
    inner = "".join(f"\n    {p}," for p in params)
    return f"{prefix}({inner}\n){ret_text}", details, ret


def is_deprecated(fn: Any) -> bool:
    try:
        return "DeprecationWarning" in inspect.getsource(fn)
    except (OSError, TypeError):
        return False


def render_callable(
    heading: Optional[str],
    prefix: str,
    fn: Any,
    route: str,
    level: int = 2,
    skip_first: bool = True,
    note: Optional[str] = None,
) -> str:
    sig, details, ret = build_signature(prefix, fn, skip_first)
    out = [f"{'#' * level} {heading}", ""] if heading else []
    if is_deprecated(fn):
        out += [
            (
                "> **Deprecated.** This method emits a `DeprecationWarning`; see the"
                " description below."
            ),
            "",
        ]
    if note:
        out += [f"> {note}", ""]
    out += ["```python", sig, "```", ""]
    doc = docstring_to_md(inspect.getdoc(fn))
    if doc:
        out += [doc, ""]
    if details:
        out += ["**Parameters**", ""]
        for name, ann, default in details:
            line = f"- {code(name)}"
            if ann is not inspect.Parameter.empty:
                line += f": {typed(ann, route)}"
            if default is not inspect.Parameter.empty:
                line += f", default {code(fmt_default(default))}"
            out.append(line)
        out.append("")
    if ret is not inspect.Signature.empty and ret is not None and ret is not NoneType:
        out += [f"**Returns** {typed(ret, route)}", ""]
    return "\n".join(out)


def public_members(cls: type) -> List[Tuple[str, Any, str]]:
    """(name, unwrapped callable, kind) for public members defined on ``cls`` itself, in source order."""
    members: List[Tuple[int, str, Any, str]] = []
    for name, raw in cls.__dict__.items():
        if name.startswith("_"):
            continue
        if isinstance(raw, property):
            fn, kind = raw.fget, "property"
        elif isinstance(raw, (staticmethod, classmethod)):
            fn, kind = raw.__func__, type(raw).__name__
        elif inspect.isfunction(raw):
            fn, kind = raw, "method"
        else:
            continue
        if fn is None:
            continue
        try:
            line = inspect.getsourcelines(fn)[1]
        except (OSError, TypeError):
            line = 10**9
        members.append((line, name, fn, kind))
    members.sort(key=lambda m: m[0])
    return [(name, fn, kind) for _, name, fn, kind in members]


def render_property(heading: str, fn: Any, route: str, level: int = 2) -> str:
    hints = resolve_hints(fn)
    ret = hints.get("return", inspect.signature(fn).return_annotation)
    out = [f"{'#' * level} {heading}", ""]
    if ret is not inspect.Signature.empty:
        out += [f"Property of type {typed(ret, route)}.", ""]
    else:
        out += ["Property.", ""]
    doc = docstring_to_md(inspect.getdoc(fn))
    if doc:
        out += [doc, ""]
    return "\n".join(out)


def render_members(
    cls: type,
    prefix: str,
    route: str,
    level: int = 2,
    only: Optional[Iterable[str]] = None,
    note_for: Optional[Dict[str, str]] = None,
) -> Tuple[str, List[str]]:
    """Render all public members of a class. Returns (markdown, method names)."""
    chunks: List[str] = []
    names: List[str] = []
    wanted = set(only) if only is not None else None
    for name, fn, kind in public_members(cls):
        if wanted is not None and name not in wanted:
            continue
        names.append(name)
        if kind == "property":
            chunks.append(render_property(f"{name}", fn, route, level))
        else:
            skip_first = kind != "staticmethod"
            chunks.append(
                render_callable(
                    name,
                    f"{prefix}.{name}",
                    fn,
                    route,
                    level,
                    skip_first=skip_first,
                    note=(note_for or {}).get(name),
                )
            )
    return "\n".join(chunks), names


def summary_table(cls: type, names: Iterable[str]) -> str:
    rows = ["| Method | Description |", "|--------|-------------|"]
    for name in names:
        raw = cls.__dict__.get(name)
        fn = getattr(raw, "fget", None) or getattr(raw, "__func__", None) or raw
        rows.append(
            f"| [{code(name)}](#{slug(name)}) |"
            f" {cell(first_line(inspect.getdoc(fn)))} |"
        )
    return "\n".join(rows)


# --------------------------------------------------------------------------- #
# Pages
# --------------------------------------------------------------------------- #


def resource_attrs() -> Dict[str, type]:
    """Map ``client.<attr>`` to the implementing class, from ``APIClient.__init__``."""
    src = inspect.getsource(APIClient.__init__)
    mapping: Dict[str, type] = {}
    for m in re.finditer(r"self\.(\w+)\s*=\s*(\w+)\(self\)", src):
        cls = getattr(client_module, m.group(2), None)
        if inspect.isclass(cls) and issubclass(cls, APIResourse):
            mapping[m.group(1)] = cls
    return mapping


def resource_pages(out: Path, route: str) -> List[Tuple[str, str]]:
    attrs = resource_attrs()
    public = [a for a in attrs if not a.startswith("_")]
    for attr in DISPATCHED:
        if attr not in public:
            public.append(attr)
    order = [a for a in PREFERRED_ORDER if a in public] + sorted(
        a for a in public if a not in PREFERRED_ORDER
    )

    pages: List[Tuple[str, str]] = []
    for attr in order:
        if attr in DISPATCHED:
            primary_attr, legacy_attr = DISPATCHED[attr]
            primary, legacy = attrs[primary_attr], attrs[legacy_attr]
        else:
            primary, legacy = attrs[attr], None

        prefix = f"client.{attr}"
        blurb = first_line(own_doc(primary)) or RESOURCE_BLURBS.get(
            attr, f"Operations exposed by {prefix}."
        )
        body = [frontmatter(prefix, blurb)]
        body.append(
            f"Accessed as {code(prefix)} on an [APIClient]({route}/client). "
            f"Implemented by {code(primary.__module__ + '.' + primary.__name__)}."
        )
        body.append("")
        if legacy is not None:
            prop = getattr(APIClient, attr)
            body.append(docstring_to_md(inspect.getdoc(prop.fget)))
            body.append("")
        class_doc = docstring_to_md(own_doc(primary))
        if class_doc:
            body += [class_doc, ""]

        primary_names = [n for n, _, _ in public_members(primary)]
        legacy_names = [n for n, _, _ in public_members(legacy)] if legacy else []
        only_primary = [
            n for n in primary_names if legacy is not None and n not in legacy_names
        ]
        only_legacy = [n for n in legacy_names if n not in primary_names]

        body += ["## Methods", "", summary_table(primary, primary_names), ""]
        if only_legacy:
            body += [
                f"Methods only available on the legacy {code(legacy.__name__)}: "
                + ", ".join(f"[{code(n)}](#{slug(n)})" for n in only_legacy)
                + ".",
                "",
            ]
        notes = {
            n: (
                "Only available when the workspace uses the new"
                f" {code(primary.__name__)}."
            )
            for n in only_primary
        }
        rendered, _ = render_members(primary, prefix, route, level=2, note_for=notes)
        body += [rendered, ""]
        if only_legacy:
            legacy_note = {
                n: (
                    f"Only available on the legacy {code(legacy.__name__)}, used when"
                    " the new API flag is off."
                )
                for n in only_legacy
            }
            rendered, _ = render_members(
                legacy, prefix, route, level=2, only=only_legacy, note_for=legacy_note
            )
            body += [rendered, ""]

        page_dir = out / attr
        page_dir.mkdir(parents=True, exist_ok=True)
        (page_dir / "index.mdx").write_text("\n".join(body).rstrip() + "\n")
        pages.append((attr, blurb))
    return pages


def client_page(out: Path, route: str, resources: List[Tuple[str, str]]) -> None:
    body = [
        frontmatter(
            "APIClient",
            "Entry point of the SDK: connects to a workspace and exposes one attribute"
            " per resource group.",
        )
    ]
    body += [
        "```python",
        "from leptonai.api.v2 import APIClient",
        "",
        (
            "client = APIClient()  # workspace from `lep login` or LEPTON_WORKSPACE_*"
            " env vars"
        ),
        'client = APIClient(workspace_id="my-workspace", auth_token="...")',
        "```",
        "",
        docstring_to_md(own_doc(APIClient)),
        "",
        "## Constructor",
        "",
        render_callable(None, "APIClient", APIClient.__init__, route),
        "## Resource groups",
        "",
        "| Attribute | Description |",
        "|-----------|-------------|",
    ]
    for attr, blurb in resources:
        body.append(f"| [{code('client.' + attr)}]({route}/{attr}) | {cell(blurb)} |")
    body.append("")

    members = public_members(APIClient)
    props = [(n, fn) for n, fn, kind in members if kind == "property"]
    methods = [(n, fn, kind) for n, fn, kind in members if kind != "property"]
    if props:
        body += ["## Properties", ""]
        for name, fn in props:
            body += [render_property(name, fn, route, level=3), ""]
    if methods:
        body += ["## Methods", ""]
        for name, fn, kind in methods:
            body += [
                render_callable(
                    name,
                    f"client.{name}",
                    fn,
                    route,
                    level=3,
                    skip_first=kind != "staticmethod",
                ),
                "",
            ]

    funcs = [
        (n, obj)
        for n in getattr(api_v2, "__all__", [])
        for obj in [getattr(api_v2, n, None)]
        if inspect.isfunction(obj)
    ]
    if funcs:
        body += ["## Module functions", ""]
        for name, fn in funcs:
            body += [
                render_callable(
                    name,
                    f"leptonai.api.v2.{name}",
                    fn,
                    route,
                    level=3,
                    skip_first=False,
                ),
                "",
            ]

    errors = [
        (n, obj)
        for n in getattr(api_v2, "__all__", [])
        for obj in [getattr(api_v2, n, None)]
        if inspect.isclass(obj) and issubclass(obj, BaseException)
    ]
    if errors:
        body += [
            "## Errors",
            "",
            "All of these are importable from {}.".format(code("leptonai.api.v2")),
            "",
            "| Error | Base | Description |",
            "|-------|------|-------------|",
        ]
        for name, cls in errors:
            base = cls.__bases__[0].__name__
            body.append(
                f"| {code(name)} | {code(base)} | {cell(first_line(own_doc(cls)))} |"
            )
        body.append("")

    body += [
        "## WorkspaceRecord",
        "",
        (
            f"Importable as {code('leptonai.api.v2.WorkspaceRecord')}. Manages the"
            f" workspaces saved locally by {code('lep login')}."
        ),
        "",
        docstring_to_md(own_doc(WorkspaceRecord)),
        "",
    ]
    rendered, _ = render_members(WorkspaceRecord, "WorkspaceRecord", route, level=3)
    body += [rendered, ""]

    page_dir = out / "client"
    page_dir.mkdir(parents=True, exist_ok=True)
    (page_dir / "index.mdx").write_text("\n".join(body).rstrip() + "\n")


def endpoint_client_page(out: Path, route: str) -> None:
    import leptonai.client as ep

    body = [
        frontmatter(
            "Client (call an endpoint)",
            "Call a deployed endpoint like a Python function. Methods are generated"
            " from the endpoint's OpenAPI schema.",
        ),
        "```python",
        "from leptonai.client import Client, local, current",
        "",
        'c = Client("my-workspace", "my-endpoint", token="MY_TOKEN")',
        "c.paths()          # list the endpoint's routes",
        "c.run(inputs=...)  # call the route named `run`",
        "```",
        "",
        docstring_to_md(own_doc(ep.Client)),
        "",
        "## Constructor",
        "",
        render_callable(None, "Client", ep.Client.__init__, route),
        "## Methods",
        "",
    ]
    rendered, _ = render_members(ep.Client, "c", route, level=3)
    body += [rendered, "", "## Helper functions", ""]
    for name in ("local", "current"):
        fn = getattr(ep, name, None)
        if inspect.isfunction(fn):
            body += [
                render_callable(
                    name,
                    f"leptonai.client.{name}",
                    fn,
                    route,
                    level=3,
                    skip_first=False,
                ),
                "",
            ]

    page_dir = out / "endpoint-client"
    page_dir.mkdir(parents=True, exist_ok=True)
    (page_dir / "index.mdx").write_text("\n".join(body).rstrip() + "\n")


def field_rows(model: type, route: str) -> List[str]:
    rows = [
        "| Field | Type | Required | Default | Description |",
        "|-------|------|----------|---------|-------------|",
    ]
    for name, info in model.model_fields.items():
        label = code(name)
        if info.alias and info.alias != name:
            label += f" (JSON {code(info.alias)})"
        if info.default_factory is not None:
            default = "factory"
        elif info.default is PydanticUndefined:
            default = ""
        else:
            default = code(fmt_default(info.default))
        required = "yes" if info.is_required() else "no"
        desc = cell(info.description or "")
        type_text = typed(info.annotation, route).replace("|", "\\|")
        rows.append(f"| {label} | {type_text} | {required} | {default} | {desc} |")
    return rows


def types_pages(out: Path, route: str) -> List[str]:
    types_dir = out / "types"
    types_dir.mkdir(parents=True, exist_ok=True)
    modules: List[str] = []
    for mod_info in sorted(
        pkgutil.iter_modules(sdk_types.__path__), key=lambda m: m.name
    ):
        if mod_info.name.startswith("_"):
            continue
        mod = importlib.import_module(f"{sdk_types.__name__}.{mod_info.name}")
        classes = []
        for name, cls in inspect.getmembers(mod, inspect.isclass):
            if cls.__module__ != mod.__name__ or name.startswith("_"):
                continue
            if not (issubclass(cls, BaseModel) or issubclass(cls, enum.Enum)):
                continue
            try:
                line = inspect.getsourcelines(cls)[1]
            except (OSError, TypeError):
                line = 10**9
            classes.append((line, name, cls))
        if not classes:
            continue
        classes.sort()
        names = [n for _, n, _ in classes]
        body = [
            frontmatter(
                f"types.{mod_info.name}",
                first_line(mod.__doc__)
                or f"Data types in leptonai.api.v2.types.{mod_info.name}.",
            ),
            "```python",
            f"from {mod.__name__} import (",
            *[f"    {n}," for n in names],
            ")",
            "```",
            "",
        ]
        mod_doc = docstring_to_md(mod.__doc__)
        if mod_doc:
            body += [mod_doc, ""]
        body += [
            "| Type | Kind | Description |",
            "|------|------|-------------|",
        ]
        for _, name, cls in classes:
            kind = "enum" if issubclass(cls, enum.Enum) else "model"
            body.append(
                f"| [{code(name)}](#{slug(name)}) | {kind} |"
                f" {cell(first_line(own_doc(cls)))} |"
            )
        body.append("")
        for _, name, cls in classes:
            body += [f"## {name}", ""]
            parents = [b for b in cls.__bases__ if is_sdk_type(b)]
            if parents:
                body.append(
                    "Extends "
                    + ", ".join(
                        f"[{code(b.__name__)}]({type_link(b, route)})" for b in parents
                    )
                    + "."
                )
                body.append("")
            doc = docstring_to_md(own_doc(cls))
            if doc:
                body += [doc, ""]
            if issubclass(cls, enum.Enum):
                body += ["| Member | Value |", "|--------|-------|"]
                for member in cls:
                    body.append(f"| {code(member.name)} | {code(repr(member.value))} |")
                body.append("")
            else:
                if cls.model_fields:
                    body += field_rows(cls, route) + [""]
                else:
                    body += ["This model has no fields.", ""]
        page_dir = types_dir / mod_info.name
        page_dir.mkdir(parents=True, exist_ok=True)
        (page_dir / "index.mdx").write_text("\n".join(body).rstrip() + "\n")
        modules.append(mod_info.name)

    (types_dir / "meta.json").write_text(
        json.dumps({"title": "Types", "pages": modules}, indent=2) + "\n"
    )
    return modules


def clean(out: Path) -> int:
    removed = 0
    for path in out.rglob("index.mdx"):
        if path.parent == out:
            continue
        if MARKER in path.read_text():
            path.unlink()
            removed += 1
    # Page directories empty out first; then meta.json files left alone in a
    # directory go, and finally the directories themselves.
    remove_empty_dirs(out)
    for path in sorted(
        out.rglob("meta.json"), key=lambda p: len(p.parts), reverse=True
    ):
        if path.parent != out and all(p == path for p in path.parent.iterdir()):
            path.unlink()
    remove_empty_dirs(out)
    return removed


def remove_empty_dirs(out: Path) -> None:
    for path in sorted(
        (p for p in out.rglob("*") if p.is_dir()),
        key=lambda p: len(p.parts),
        reverse=True,
    ):
        if not any(path.iterdir()):
            path.rmdir()


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--out",
        required=True,
        type=Path,
        help="reference/api content directory of the docs site",
    )
    parser.add_argument(
        "--route", default="/reference/api", help="URL route of --out on the docs site"
    )
    parser.add_argument(
        "--clean-only",
        action="store_true",
        help="remove previously generated pages and the meta.json files, then exit",
    )
    args = parser.parse_args()

    out: Path = args.out
    out.mkdir(parents=True, exist_ok=True)
    removed = clean(out)
    if args.clean_only:
        meta = out / "meta.json"
        if meta.exists():
            meta.unlink()
        print(f"removed {removed} generated pages under {out}")
        return

    resources = resource_pages(out, args.route)
    client_page(out, args.route, resources)
    endpoint_client_page(out, args.route)
    modules = types_pages(out, args.route)

    pages = (
        ["index", "client"]
        + [attr for attr, _ in resources]
        + ["endpoint-client", "types"]
    )
    (out / "meta.json").write_text(
        json.dumps(
            {"root": True, "title": "Python SDK Reference", "pages": pages}, indent=2
        )
        + "\n"
    )

    written = sorted(
        str(p.relative_to(out))
        for p in out.rglob("index.mdx")
        if MARKER in p.read_text()
    )
    print(
        f"leptonai {leptonai.__version__}: removed {removed} stale pages, wrote"
        f" {len(written)} pages ({len(resources)} resource groups, {len(modules)} type"
        f" modules) under {out}"
    )


if __name__ == "__main__":
    main()
