apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: leptondeployments.lepton.ai
spec:
  group: lepton.ai
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec: 
              type: object
              properties:
                id:
                  type: string
                name:
                  type: string
                photon_id:
                  type: string
                model_id:
                  type: string
                created_at:
                  type: integer
                status:
                  type: object
                  properties:
                    state:
                      type: string
                    endpoint:
                      type: object
                      properties:
                        internal_endpoint:
                          type: string
                        external_endpoint:
                          type: string
                resource_requirement:
                  type: object
                  properties:
                    cpu:
                      type: number
                    memory:
                      type: integer
                    accelerator_type:
                      type: string
                    accelerator_num:
                      type: number
                    min_replicas:
                      type: integer
  scope: Namespaced
  names:
    plural: leptondeployments
    singular: leptondeployment
    kind: LeptonDeployment
    shortNames:
      - ld