apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  hostNetwork: true
  tolerations:
    - key: virtual-kubelet.io/provider
      operator: Equal
      value: ec2
      effect: NoSchedule
  containers:
    - name: nginx
      image: nginx:latest
