name: benchmark

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - .github/**
      - sdk/**
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -U pip setuptools
    - name: Run Benchmark
      run: |
        cd sdk
        pip install -e .
        cd leptonai/bench/gpt2
        pip install -r requirements.txt
        ./run.sh 8088
