name: CD - Deploy main branch to EKS dev-staging cluster default namespace

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set short git commit SHA
      id: vars
      run: |
        calculatedSha=$(git rev-parse --short HEAD)
        echo "short_sha=$calculatedSha" >> $GITHUB_OUTPUT
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Switch to the proper k8s context
      run: aws eks update-kubeconfig --name ${{ vars.K8S_DEV_STAGING }} --region ${{ vars.AWS_REGION }}
    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
          version: 'v3.11.3'
      id: install
    - name: Build Lepton API server Docker image
      env:
        ECR_REPOSITORY: lepton-api-server
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ steps.vars.outputs.short_sha }}
      run: |
        docker build . --file lepton-api-server/Dockerfile --tag $ECR_REPOSITORY:$IMAGE_TAG
        docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    - name: Build Lepton web Docker image
      env:
        ECR_REPOSITORY: lepton-web
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ steps.vars.outputs.short_sha }}
      run: |
        docker build web --file web/Dockerfile --tag $ECR_REPOSITORY:$IMAGE_TAG
        docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    - name: Helm upgrade charts
      run: |
        # Not to setting the image tag here to avoid having to update here when, in the
        # future, we update flags of the helm charts, because if we set image tag, we
        # must set all flags. As a result, this commend will shortly set the image tag
        # to `:latest` and then the image tag will be updated to the correct one in the
        # following step.
        helm upgrade lepton charts/lepton
    - name: Deploy Lepton API server and web
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DEV_STAGING }}
        API_SERVER_ECR_REPOSITORY: lepton-api-server
        WEB_ECR_REPOSITORY: lepton-web
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ steps.vars.outputs.short_sha }}
      run: |
        kubectl set image deployment/$API_SERVER_ECR_REPOSITORY $API_SERVER_ECR_REPOSITORY=$ECR_REGISTRY/$API_SERVER_ECR_REPOSITORY:$IMAGE_TAG
        kubectl set image deployment/$WEB_ECR_REPOSITORY $WEB_ECR_REPOSITORY=$ECR_REGISTRY/$WEB_ECR_REPOSITORY:$IMAGE_TAG
