name: CI/CD - workspace

env:
  # override in-cluster config
  KUBECONFIG: /home/runner/.kube/config
  POD_NAMESPACE: default

on:
  push:
    branches: [ "main" ]

jobs:
  build-api-server:
    uses: ./.github/workflows/build-docker-image.yaml
    secrets: inherit
    with:
      folder: api-server
      repo: lepton-api-server

  build-deployment-operator:
    uses: ./.github/workflows/build-docker-image.yaml
    secrets: inherit
    with:
      folder: deployment-operator
      repo: lepton-deployment-operator

  e2e-tests:
    needs: [build-api-server, build-deployment-operator]
    uses: ./.github/workflows/run-e2e-tests.yaml
    secrets: inherit

  build-api-server-latest:
    needs: [e2e-tests]
    uses: ./.github/workflows/build-docker-image.yaml
    secrets: inherit
    with:
      folder: api-server
      repo: lepton-api-server
      tag: latest

  build-deployment-operator-latest:
    needs: [e2e-tests]
    uses: ./.github/workflows/build-docker-image.yaml
    secrets: inherit
    with:
      folder: deployment-operator
      repo: lepton-deployment-operator
      tag: latest

  build-web-latest:
    needs: [e2e-tests]
    uses: ./.github/workflows/build-docker-image.yaml
    secrets: inherit
    with:
      folder: web
      repo: lepton-web
      tag: latest

  deploy-to-dev-latest:
    runs-on: ubuntu-latest
    needs: [build-api-server-latest, build-deployment-operator-latest, build-web-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - name: Build mothership cli
      run: |
        (cd mothership && go build -v ./cmd/mothership && mv mothership ../mothershipctl)
    - name: Update the latest workspace
      env:
        WORKSPACE_NAME: latest
      run: |
        ./mothershipctl workspace update \
          --auto-approve \
          --mothership-url https://mothership.cloud.lepton.ai/api/v1 \
          --token "${{ secrets.MOTHERSHIP_TOKEN }}" \
          --workspace-name "$WORKSPACE_NAME" \
          --image-tag latest
        ./mothershipctl workspace wait \
          --mothership-url https://mothership.cloud.lepton.ai/api/v1 \
          --token "${{ secrets.MOTHERSHIP_TOKEN }}" \
          --workspace-name "$WORKSPACE_NAME" \
          --timeout 10 \
          --expected-state "ready"
