name: CI/CD - cluster

on:
  pull_request:
    paths:
      - .github/workflows/cicd-cluster.yaml
      - "infra/terraform/eks-lepton/**"
    branches: [ "**" ]

jobs:
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set short git commit SHA
      id: vars
      run: |
        calculatedSha=$(git rev-parse --short HEAD)
        echo "cluster_name=testcl$calculatedSha" >> $GITHUB_OUTPUT
        echo "workspace_name=testws$calculatedSha" >> $GITHUB_OUTPUT
        echo "api_token=token-$calculatedSha" >> $GITHUB_OUTPUT
        echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - name: Install Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Build mothership cli
      run: |
        (cd lepton-mothership && go build -v ./cmd/mothership && mv mothership ..)
    - name: Create cluster
      run: |
        ./mothership cluster create \
          --token ${{ secrets.MOTHERSHIP_TOKEN }} \
          --cluster-name ${{ steps.vars.outputs.cluster_name }} \
          --git-ref ${{ steps.vars.outputs.branch }}
        ./mothership cluster wait \
          --token ${{ secrets.MOTHERSHIP_TOKEN }} \
          --cluster-name ${{ steps.vars.outputs.cluster_name }} \
          --timeout 60 \
          --expected-state "ready"
    - name: Create workspace
      run: |
        ./mothership workspace create \
          --token "${{ secrets.MOTHERSHIP_TOKEN }}" \
          --api-token "${{ steps.vars.outputs.api_token }}" \
          --cluster-name "${{ steps.vars.outputs.cluster_name }}" \
          --workspace-name "${{ steps.vars.outputs.workspace_name }}" \
          --git-ref "${{ steps.vars.outputs.branch }}"
        ./mothership workspace wait \
          --token "${{ secrets.MOTHERSHIP_TOKEN }}" \
          --workspace-name "${{ steps.vars.outputs.workspace_name }}" \
          --timeout 10 \
          --expected-state "ready"
    - name: Run e2e tests
      run: |
        pip install -e ./sdk
        e2e-tests/push-and-deploy.sh \
          ${{ steps.vars.outputs.api_token }} \
          https://${{ steps.vars.outputs.workspace_name }}.cloud.lepton.ai/api/v1
    - name: Delete workspace
      if: always()
      run: |
        ./mothership workspace delete \
          --token "${{ secrets.MOTHERSHIP_TOKEN }}" \
          --workspace-name "${{ steps.vars.outputs.workspace_name }}"
        ./mothership workspace wait \
          --token "${{ secrets.MOTHERSHIP_TOKEN }}" \
          --workspace-name "${{ steps.vars.outputs.workspace_name }}" \
          --timeout 10 \
          --expected-state "deleted"
    - name: Delete cluster
      if: always()
      run: |
        ./mothership cluster delete \
          --token "${{ secrets.MOTHERSHIP_TOKEN }}" \
          --cluster-name "${{ steps.vars.outputs.cluster_name }}"
        ./mothership cluster wait \
          --token "${{ secrets.MOTHERSHIP_TOKEN }}" \
          --cluster-name "${{ steps.vars.outputs.cluster_name }}" \
          --timeout 60 \
          --expected-state "deleted"
