name: weekly-create-ci-cluster

on:
  schedule:
  # create a new ci cluster every week on Sunday 8am UTC
  - cron: "0 8 * * 0"

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - run: |
        # TODO: use mothershp cli to create cluster
        name=ci$(date +%Y%m%d%H%M%S)
        echo "Creating cluster $name"
        curl -H "Authorization: Bearer ${{ secrets.MOTHERSHIP_TOKEN }}" -X POST \
          -d '{
                "deployment_environment":"TEST",
                "name":"'$name'"
              }' \
          https://mothership.cloud.lepton.ai/api/v1/clusters
