name: CI/CD - cluster

on:
  pull_request:
    paths:
      - .github/workflows/cicd-cluster.yaml
      - "infra/terraform/eks-lepton/**"
    branches: [ "**" ]

jobs:
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set short git commit SHA
      id: vars
      run: |
        calculatedSha=$(git rev-parse --short HEAD)
        echo "cluster_name=testcl$calculatedSha" >> $GITHUB_OUTPUT
        echo "workspace_name=testws$calculatedSha" >> $GITHUB_OUTPUT
        echo "api_token=token-$calculatedSha" >> $GITHUB_OUTPUT
        echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - name: Install Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Build mothership cli
      run: |
        (cd mothership && go build -v ./cmd/mothership && mv mothership ../mothershipctl)
    - name: Create cluster
      run: |
        ./mothershipctl cluster create \
          --mothership-url https://mothership.cloud.lepton.ai/api/v1 \
          --token ${{ secrets.MOTHERSHIP_TOKEN }} \
          --cluster-name ${{ steps.vars.outputs.cluster_name }} \
          --git-ref ${{ steps.vars.outputs.branch }} \
          --deployment-environment TEST

        # TODO: lower the 130min timeout below once EKS service makes cluster creation faster...
        # TODO: lower the 130min timeout below once mothership supports cancel API for ongoing jobs
        # sometimes it randomly takes over 1-hour
        # and current mothership job timeout is 120-minute anyways
        # you can't cancel or delete before the job timeout anyways
        # without cancel API, the subsequent delete step will fail!
        # for now just let it timeout so that the following delete can cleanly
        # delete the failed clusters
        ./mothershipctl cluster wait \
          --mothership-url https://mothership.cloud.lepton.ai/api/v1 \
          --token ${{ secrets.MOTHERSHIP_TOKEN }} \
          --cluster-name ${{ steps.vars.outputs.cluster_name }} \
          --timeout 130 \
          --expected-state "ready"
    - name: Create workspace
      run: |
        ./mothershipctl workspace create \
          --mothership-url https://mothership.cloud.lepton.ai/api/v1 \
          --token "${{ secrets.MOTHERSHIP_TOKEN }}" \
          --api-token "${{ steps.vars.outputs.api_token }}" \
          --cluster-name "${{ steps.vars.outputs.cluster_name }}" \
          --workspace-name "${{ steps.vars.outputs.workspace_name }}" \
          --git-ref "${{ steps.vars.outputs.branch }}"
        ./mothershipctl workspace wait \
          --mothership-url https://mothership.cloud.lepton.ai/api/v1 \
          --token "${{ secrets.MOTHERSHIP_TOKEN }}" \
          --workspace-name "${{ steps.vars.outputs.workspace_name }}" \
          --timeout 10 \
          --expected-state "ready"
    - name: Run e2e tests
      run: |
        pip install -e ./sdk
        go test -timeout 3600s -v ./e2e-tests/... \
          --workspace-url https://${{ steps.vars.outputs.workspace_name }}.cloud.lepton.ai/api/v1 \
          --auth-token ${{ steps.vars.outputs.api_token }}
    - name: Delete workspace
      if: always()
      run: |
        ./mothershipctl workspace delete \
          --auto-approve \
          --mothership-url https://mothership.cloud.lepton.ai/api/v1 \
          --token "${{ secrets.MOTHERSHIP_TOKEN }}" \
          --workspace-name "${{ steps.vars.outputs.workspace_name }}"
        ./mothershipctl workspace wait \
          --mothership-url https://mothership.cloud.lepton.ai/api/v1 \
          --token "${{ secrets.MOTHERSHIP_TOKEN }}" \
          --workspace-name "${{ steps.vars.outputs.workspace_name }}" \
          --timeout 10 \
          --expected-state "deleted"
    - name: Delete cluster
      if: always()
      run: |
        ./mothershipctl cluster delete \
          --auto-approve \
          --mothership-url https://mothership.cloud.lepton.ai/api/v1 \
          --token "${{ secrets.MOTHERSHIP_TOKEN }}" \
          --cluster-name "${{ steps.vars.outputs.cluster_name }}"
        ./mothershipctl cluster wait \
          --mothership-url https://mothership.cloud.lepton.ai/api/v1 \
          --token "${{ secrets.MOTHERSHIP_TOKEN }}" \
          --cluster-name "${{ steps.vars.outputs.cluster_name }}" \
          --timeout 60 \
          --expected-state "deleted"
