name: CI/CD - workspace

on:
  push:
    branches: [ "release-**" ]

jobs:
  build-api-server:
    uses: ./.github/workflows/build-docker-image.yaml
    secrets: inherit
    with:
      folder: api-server
      repo: lepton-api-server

  build-deployment-operator:
    uses: ./.github/workflows/build-docker-image.yaml
    secrets: inherit
    with:
      folder: deployment-operator
      repo: lepton-deployment-operator

  e2e-tests:
    needs: [build-api-server, build-deployment-operator]
    uses: ./.github/workflows/run-e2e-tests.yaml
    secrets: inherit
