name: CI/CD - mothership

on:
  pull_request:
    paths:
      - ".github/workflows/cicd-mothership-pr.yaml"
      - ".github/workflows/build-docker-image.yaml"
      - "mothership/**"
      - "go-pkg/**"
    branches: [ "**" ]

jobs:
  build-mothership:
    uses: ./.github/workflows/build-docker-image.yaml
    secrets: inherit
    with:
      folder: mothership
      repo: lepton-mothership

  build-mothershipctl:
    uses: ./.github/workflows/build-docker-image.yaml
    secrets: inherit
    with:
      folder: mothership/cmd/mothership
      repo: lepton-mothershipctl
