name: CI/CD - workspace

on:
  pull_request:
    paths:
      - ".github/workflows/build-docker-image.yaml"
      - ".github/workflows/cicd-workspace-pr.yaml"
      - ".github/workflows/run-e2e-tests.yaml"
      - "**.go"
      - "**.py"
      - "charts/lepton/**"
      - "infra/terraform/workspace/**"
    branches: [ "**" ]

jobs:
  build-api-server:
    uses: ./.github/workflows/build-docker-image.yaml
    secrets: inherit
    with:
      folder: api-server
      repo: lepton-api-server

  build-deployment-operator:
    uses: ./.github/workflows/build-docker-image.yaml
    secrets: inherit
    with:
      folder: deployment-operator
      repo: lepton-deployment-operator

  e2e-tests:
    needs: [build-api-server, build-deployment-operator]
    uses: ./.github/workflows/run-e2e-tests.yaml
    secrets: inherit
