name: CI/CD - mothership - release

on:
  push:
    tags:
      - '*'

jobs:
  build-mothership:
    uses: ./.github/workflows/build-docker-image.yaml
    secrets: inherit
    with:
      folder: mothership
      repo: lepton-mothership
      tag: ${GITHUB_REF##*/}
      commit: ${GITHUB_REF##*/}

  build-mothershipctl:
    uses: ./.github/workflows/build-docker-image.yaml
    secrets: inherit
    with:
      folder: mothership/cmd/mothership
      repo: lepton-mothershipctl
      tag: ${GITHUB_REF##*/}
      commit: ${GITHUB_REF##*/}
