name: web

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - .github/**
      - web/**
    branches: [ "**" ]

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: web/node_modules
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        working-directory: web
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

  lint:
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Restore node modules cache
        uses: actions/cache@v3
        with:
          path: web/node_modules
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Lint
        working-directory: web
        run: npm run lint

  test:
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Restore node modules cache
        uses: actions/cache@v3
        with:
          path: web/node_modules
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Run test task
        working-directory: web
        run: npm run test
  build:
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Restore node modules cache
        uses: actions/cache@v3
        with:
          path: web/node_modules
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Run build task
        working-directory: web
        run: npm run build --if-present
