name: Build and Deploy Photon Runner Docker Images

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Photon Runner Version'

jobs:
  build_matrix:
    strategy:
      matrix:
        python_version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build and Deploy
      env:
        ECR_REPOSITORY: lepton
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        VERSION_TAG: ${{ github.event.inputs.version || github.sha }}
      run: |
        echo "HEAD SHA=$(git rev-parse --short HEAD)"
        echo "VERSION_TAG=${VERSION_TAG}"
        echo "Building for python_version=${{ matrix.python_version }}"
        tag="${ECR_REGISTRY}/${ECR_REPOSITORY}:photon-py${{ matrix.python_version }}-runner-${VERSION_TAG}"
        cd sdk
        docker build . --build-arg PYTHON_VERSION=${{ matrix.python_version }} --file leptonai/photon/dockerfiles/python-runner.Dockerfile --tag ${tag}
        docker push ${tag}
        docker rmi ${tag}
