name: release

on:
  push:
    branches: ["main"]
  pull_request:
    paths:
      - .github/workflows/release.yaml
    branches: ["**"]
  workflow_dispatch:
    inputs:
      publish_pypi:
        description: "Whether publish to PyPI"
        type: boolean
        default: false
      is_release:
        description: "Is this a release package"
        type: boolean
        default: false
      run_e2e:
        description: "Whether run end to end testing"
        type: boolean
        default: false

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Set up pip
        run: |
          pip install -U pip setuptools
      - name: Build Package
        id: build-package
        run: |
          pip wheel --no-deps .
      - name: Upload to Github Artifact
        uses: actions/upload-artifact@v4
        with:
          name: whl-package
          path: leptonai*.whl

  test-package:
    needs: build-package
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            python_version: "3.10"
          - runner: macos-latest
            python_version: "3.12"
          - runner: ubuntu-latest
            python_version: "3.13"
    runs-on: ${{matrix.runner}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python_version }}"
      - name: Set up pip
        run: |
          pip install -U pip setuptools
      - uses: actions/download-artifact@v4
        with:
          name: whl-package
      - name: Install Package
        run: |
          pip install leptonai*.whl
      - name: Run Basic Tests
        run: |
          echo "leptonai package version:"
          lep -v
          lep ph create -n gpt2 -m hf:gpt2

          cd ..
          echo "leptonai package path:"
          python -c "import leptonai; print(leptonai)"
          cd -
      - name: Run Runtime Tests
        run: |
          whl_file=(leptonai*.whl)
          pip install ${whl_file}[runtime] ${whl_file}[test]
          cd ..
          echo "Run unittests"
          pytest -x leptonai
          cd -
      - name: Run End-To-End Tests
        if: inputs.run_e2e
        env:
          LEPTON_RELEASE_CREDENTIALS: ${{ secrets.LEPTON_STAGING_WORKSPACE_CREDENTIALS }}
        run: bash release_scripts/e2e_sdk_cli_test.sh

  publish-pypi:
    if: inputs.publish_pypi
    needs: test-package
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Set up pip
        run: |
          pip install -U pip setuptools
      - name: Install twine
        run: |
          pip install twine
      - uses: actions/download-artifact@v4
        with:
          name: whl-package
      - name: Upload Package to PyPI
        run: |
          twine upload --verbose --username "${{ secrets.PYPI_UPLOAD_USERNAME }}" --password "${{ secrets.PYPI_UPLOAD_PASSWORD }}" leptonai*.whl
