name: shellcheck-ci-lint

on:
  pull_request:

permissions:
    contents: read
    pull-requests: write

jobs:
  shellcheck:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          path: "."
          pattern: "*.sh"
          exclude: |
            ./.git/*
            ./tuna/*
            ./machine-rs/*
          check_all_files_with_shebangs: "false"
