name: sdk-test-cp37

on:
  pull_request:
    paths:
      - .github/workflows/test-sdk-cp37.yaml
      - sdk/**
    branches: ["**"]

permissions:
  contents: read

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
          cache: "pip" # caching pip dependencies
      - name: Install dependencies
        run: |
          pip install -U pip setuptools
      - name: Test with pytest
        run: |
          cd sdk
          if ! hash nvidia-smi 2>/dev/null; then
             echo "nvidia-smi not found on host, installing cpu version of torch"
             pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          fi
          pip install .
          pip install -r leptonai/examples/requirements.txt
          pip install .[test]
          cd -
          pytest -x sdk
