name: sdk-test-cp37

on:
  pull_request:
    paths:
      - .github/workflows/test-sdk-cp37.yaml
      - sdk/**
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        pip install -U pip setuptools
    - name: Test with pytest
      run: |
        cd sdk
        pip install .
        pip install -r leptonai/examples/requirements.txt
        pip install .[test]
        cd -
        pytest sdk/
